microservices:
  graphene-chrome:
    docker:
      dockerfile: './Dockerfile_chrome'
      customTags:
        - '67.0.3396.79-2.39-2.3.8'
      cacheFromTag: 'latest'
    buildOnChangeOf:
      paths:
      - 'Dockerfile_chrome'
  graphene-firefox:
    docker:
      dockerfile: './Dockerfile_firefox'
      customTags:
        - '69.0-0.25.0-2.3.8'
      cacheFromTag: 'latest'
    buildOnChangeOf:
      paths:
      - 'Dockerfile_firefox'
  graphene-chrome-uisdk:
    docker:
      dockerfile: './Dockerfile_chrome_uisdk'
      customTags:
        - '8.10.0'
        - 'latest'
      cacheFromTag: 'latest'
    buildOnChangeOf:
      paths:
      - 'Dockerfile_chrome_uisdk'
  graphene-firefox-uisdk:
    docker:
      dockerfile: './Dockerfile_firefox_uisdk'
      customTags:
        - '8.10.0'
        - 'latest'
      cacheFromTag: 'latest'
    buildOnChangeOf:
      paths:
      - 'Dockerfile_firefox_uisdk'
